{{- if .Values.automatic.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "personal-ovpn.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels: {{- include "personal-ovpn.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
spec:
  accessModes:
  {{- range .Values.automatic.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.automatic.persistence.size | quote }}
  {{ include "personal-ovpn.storageClass" . }}
{{- end }}
